export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMPTY_CART: 'EMPTY_CART',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ARTISAN_NOT_FOUND: 'ARTISAN_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  UNAUTHORIZED_ORDER_ACCESS: 'UNAUTHORIZED_ORDER_ACCESS',
} as const;
